spring:
  application:
    name: webapp-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/qcloud?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 1996S05y22u!
    sql-script-encoding: utf-8
    hikari:
      connection-timeout: 60000
      max-lifetime: 600000
      maximum-pool-size: 20
  redis:
    host: 47.119.187.177
    port: 6379
    password: atpx4869
    database: 0
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: false
jwt:
  period:
    web: 3600
