syntax = "proto3";
option java_multiple_files = true;
option java_outer_classname = "UserVerifyProto";
option java_package = "cn.spinq.geminipi.authorization.spinqCloudAdmin.grpc";

service UserVerifyService {
    rpc sayHello (GreetingRequest) returns (GreetingResponse);
    rpc adminVerify (AdminVerifyRequest) returns (AdminVerifyResponse);
}

message AdminVerifyRequest {
    string token = 1;
}

message AdminVerifyResponse {
    int32 status = 1;
    string msg = 2;
    int32 userid = 3;
    string username = 4;
}

message GreetingRequest {
    string first_name = 1;
    string last_name = 2;
}

message GreetingResponse {
    string message = 1;
}