#开发环境配置

server:
  # 服务IP
  address: 0.0.0.0
  # 服务端口
  port: 5500
  http-port: 5510
  ssl:
    key-store: classpath:11299147_uat-cloud.spinq.cn.jks
    key-store-password: 65sb7059
    keyStoreType: JKS

jasypt:
  encryptor:
    password: my_application_encryption_salt

aes:
  key: ENC(k9GSqRgd8ojdvMJEDgYFAmZuN3mD+QeConjcAuYC3R8=)
  salt: ENC(hWXKwMptSNJUKBAOGCNJ1/4oB32EQ7xWx8qsBKrfDjzTS5jBbsgCK+gxK2tx+J6zqyi57E8tXmLKthvE4g+4x29w/zuugeZlsTqln+L4e/U=)

spring:
  datasource:
    username: ENC(9l85lVBadOKdD9Mk5+6gbg==)
#    username: root
    password: ENC(P3HL4x8jzCfwgIbZyJ8yypS3flJ+OR6i)
#    password: 1AmP@ssw0rd
    url: jdbc:mysql://127.0.0.1:3306/gemini_pi_sit?useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&characterEncoding=utf8&allowMultiQueries=true
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 20

logging:
  config: log4j2-sit.xml

dbversion: 1

jwt:
  period: 1296000

grpc:
  client:
    tarus-server:
      #      address: static://0.0.0.0:6565
      address: static://uat-cloud.spinq.cn:6055
#      negotiation-type: plaintext
      security:
        authorityOverride: uat-cloud.spinq.cn

file-upload:
  qiniu:
    domain: "http://appsrc-cdn-dev.edu.spinq.cn/"
    bucket: cdn-spinq-app-src-dev
    app-code-release-prefix: pi-sit/appCode
    auth-barcode-release-prefix: pi-sit/authBarCode

admin:
  token: ENC(mbl5ctfzN24Df4IueLJrwBLk3wnNApS6)